apiVersion: v2
name: inteli-api
appVersion: '1.21.2'
description: A Helm chart for inteli-api
version: '1.21.2'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
dependencies:
  - name: postgresql
    version: '^10.12.2'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
