apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inteli-api.fullname" . }}-config
  labels:
    {{- include "inteli-api.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  logLevel: {{ .Values.config.logLevel }}
  dbHost: {{ include "inteli-api.postgresql.fullname" . }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName }}
  authJwksUri: {{ .Values.config.auth.jwksUri }}
  authAudience: {{ .Values.config.auth.audience }}
  authIssuer: {{ .Values.config.auth.issuer }}
  authTokenUrl: {{ .Values.config.auth.tokenUrl }}
  identityServiceHost: {{ .Values.config.identityServiceHost }}
  identityServicePort: {{ .Values.config.identityServicePort | quote }}
